// <auto-generated />
namespace AltiFinReact.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class invoicecode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(invoicecode));
        
        string IMigrationMetadata.Id
        {
            get { return "201501302134056_invoice code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
